services:
  - type: web
    name: callbreak-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        value: https://cardtrap.com,https://www.cardtrap.com,https://client-sable-delta-40.vercel.app
